# Generated by Django 4.1.5 on 2023-02-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_alter_class_options_delete_classbyday'),
        ('teachers', '0012_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='on_class',
            field=models.ManyToManyField(related_name='teacher_class', to='classes.class', verbose_name='Предмет'),
        ),
    ]
